FROM php:8.0-buster

LABEL org.opencontainers.image.title="Unit (php8.0)"
LABEL org.opencontainers.image.description="Official build of Unit for Docker."
LABEL org.opencontainers.image.url="https://unit.nginx.org"
LABEL org.opencontainers.image.source="https://github.com/nginx/unit"
LABEL org.opencontainers.image.documentation="https://unit.nginx.org/installation/#docker-images"
LABEL org.opencontainers.image.vendor="NGINX Docker Maintainers <docker-maint@nginx.com>"
LABEL org.opencontainers.image.version="1.34.2"

ARG DEBIAN_FRONTEND=noninteractive
ARG BUILD_PACKAGE="build-essential  libsqlite3-dev libonig-dev  librabbitmq-dev libfreetype6-dev libxml2-dev libicu-dev libjpeg62-turbo-dev libmcrypt-dev libsodium-dev libpq-dev libpng-dev \
libxml2-dev libzip-dev libpng-dev libmagickwand-dev libmagickcore-dev libwebp-dev libssl-dev libpcre2-dev libcurl4-openssl-dev  libgmp3-dev libexif-dev   libxpm-dev"
RUN set -eux && apt-get update  && apt-get upgrade -y && apt-get install --no-install-recommends  --no-install-suggests  -y libwebp6 libxml2 sqlite3 libonig5 librabbitmq4 postgresql-client-common \
 libsodium23 p7zip-full curl git  pkg-config imagemagick nano locales mc procps unzip iputils-ping libxslt1-dev libzip4 libzip-dev libxslt1.1  libgmp10 libexif12  libxpm4  ${BUILD_PACKAGE} \
#configure: WARNING: unrecognized options: --enable-opcache-file, --with-libzip, --with-freetype-dir, --with-jpeg-dir, --with-webp-dir, --with-png-dir, --with-gd
#RUN set -eux; \
 && docker-php-source extract \
    && php -m \
    && cd /usr/src/php \
    && ./configure --enable-embed --enable-opcache --enable-mbstring --enable-gd --with-openssl --with-config-file-scan-dir=/usr/local/etc/php/conf.d \
    --with-zlib --with-mysqli --with-pgsql --with-curl  --with-gmp  --enable-exif  --enable-ftp  --with-jpeg --with-jpeg --with-xpm \
    && pear channel-update pear.php.net \
    && pecl channel-update pecl.php.net \
    && pecl install msgpack igbinary apcu redis  imagick memcache-8.2 amqp \
    && docker-php-ext-enable msgpack igbinary apcu redis imagick memcache amqp \
    && docker-php-ext-install intl pdo_mysql xsl zip soap bcmath sockets pdo_pgsql zip gettext \
    #    && rm -rf /var/lib/apt/lists/*
    && make -j "$(nproc)" \
    && make install \
    && cp /usr/local/etc/php/php.ini-development /usr/local/lib/php.ini \
    && echo 'apc.enabled=1' >> /usr/local/lib/php.ini && echo 'apc.enable_cli=1' >> /usr/local/lib/php.ini && echo 'date.timezone=Europe/Moscow' >> /usr/local/lib/php.ini \
    && curl -s https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer \
    && sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen \
    && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen \
    && sed -i 's/^# *\(de_DE.UTF-8\)/\1/' /etc/locale.gen \
    && sed -i 's/^# *\(ru_RU.UTF-8\)/\1/' /etc/locale.gen \
    && locale-gen && update-locale LANG=en_US.utf8 LC_ALL=en_US.utf8 LANGUAGE=en_US.utf8 \
#RUN set -ex \
    && savedAptMark="$(apt-mark showmanual)" \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y ca-certificates git build-essential libssl-dev libpcre2-dev curl pkg-config \
    && mkdir -p /usr/lib/unit/modules /usr/lib/unit/debug-modules \
    && mkdir -p /usr/src/unit \
    && cd /usr/src/unit \
    && git clone --depth 1 -b 1.34.2 https://github.com/nginx/unit \
    && cd unit \
    && NCPU="$(getconf _NPROCESSORS_ONLN)" \
    && DEB_HOST_MULTIARCH="$(dpkg-architecture -q DEB_HOST_MULTIARCH)" \
    && CC_OPT="$(DEB_BUILD_MAINT_OPTIONS="hardening=+all,-pie" DEB_CFLAGS_MAINT_APPEND="-Wp,-D_FORTIFY_SOURCE=2 -fPIC" dpkg-buildflags --get CFLAGS)" \
    && LD_OPT="$(DEB_BUILD_MAINT_OPTIONS="hardening=+all,-pie" DEB_LDFLAGS_MAINT_APPEND="-Wl,--as-needed -pie" dpkg-buildflags --get LDFLAGS)" \
    && CONFIGURE_ARGS_MODULES="--prefix=/usr \
                --statedir=/var/lib/unit \
                --control=unix:/var/run/control.unit.sock \
                --runstatedir=/var/run \
                --pid=/var/run/unit.pid \
                --logdir=/var/log \
                --log=/var/log/unit.log \
                --tmpdir=/var/tmp \
                --user=unit \
                --group=unit \
                --openssl \
                --libdir=/usr/lib/$DEB_HOST_MULTIARCH" \
    && CONFIGURE_ARGS="$CONFIGURE_ARGS_MODULES \
                --njs" \
    && make -j $NCPU -C pkg/contrib .njs \
    && export PKG_CONFIG_PATH=$(pwd)/pkg/contrib/njs/build \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --ld-opt="$LD_OPT" --modulesdir=/usr/lib/unit/debug-modules --debug \
    && make -j $NCPU unitd \
    && install -pm755 build/sbin/unitd /usr/sbin/unitd-debug \
    && make clean \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --ld-opt="$LD_OPT" --modulesdir=/usr/lib/unit/modules \
    && make -j $NCPU unitd \
    && install -pm755 build/sbin/unitd /usr/sbin/unitd \
    && make clean \
    && /bin/true \
    && ./configure $CONFIGURE_ARGS_MODULES --cc-opt="$CC_OPT" --modulesdir=/usr/lib/unit/debug-modules --debug \
    && ./configure php \
    && make -j $NCPU php-install \
    && make clean \
    && ./configure $CONFIGURE_ARGS_MODULES --cc-opt="$CC_OPT" --modulesdir=/usr/lib/unit/modules \
    && ./configure php \
    && make -j $NCPU php-install \
    && cd \
    && rm -rf /usr/src/unit \
    && for f in /usr/sbin/unitd /usr/lib/unit/modules/*.unit.so; do \
        ldd $f | awk '/=>/{print $(NF-1)}' | while read n; do dpkg-query -S $n; done | sed 's/^\([^:]\+\):.*$/\1/' | sort | uniq >> /requirements.apt; \
       done \
    && apt-mark showmanual | xargs apt-mark auto > /dev/null \
    && { [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; } \
    && ldconfig \
    && mkdir -p /var/lib/unit/ \
    && mkdir -p /docker-entrypoint.d/ \
    && groupadd --gid 999 unit \
    && useradd \
         --uid 999 \
         --gid unit \
         --no-create-home \
         --home /nonexistent \
         --comment "unit user" \
         --shell /bin/false \
         unit \
    && apt-get update \
    && apt-get --no-install-recommends --no-install-suggests -y install curl $(cat /requirements.apt) \
    && apt-get purge -y --auto-remove build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && rm -f /requirements.apt \
    && ln -sf /dev/stderr /var/log/unit.log

COPY docker-entrypoint.sh /usr/local/bin/
COPY welcome.* /usr/share/unit/welcome/

STOPSIGNAL SIGTERM

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
EXPOSE 80
CMD ["unitd", "--no-daemon", "--control", "unix:/var/run/control.unit.sock"]
